spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.SQLServer2014Dialect
  datasource:
    url: jdbc:sqlserver://192.168.1.10\MEDINASQL:1433;databaseName=_ВРАЧЕБНАЯ ПРАКТИКА_
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: user
    password: prolog0580
  show-sql: true

sheet-file-path: \\\\192.168.1.10\\Server\\Общие папки\\Автоматизация\\Анализ направлений\\Новая аналитика тест\\